#!/bin/bash

# quick access to this on AWSlOGS:
# https://eu-central-1.console.aws.amazon.com/cloudwatch/home?region=eu-central-1#logEventViewer:group=/var/log/messages;filter=%22create-timelapse%22;start=P1D

# dont do anything if process is already running
if [ $(pgrep -f ${0} | wc -l) -gt 2 ]; then
    echo "[ERR] Process of ${0} is already running"
    exit
fi

if [ -z "$1" ]; then
    echo "[ERR] Please specify \$1 parameter. Typically this is 'cam1'"
    exit
fi

loggertitle="$(basename ${0})[$$]"

CONFIG=$(cat /etc/rpi.json)
CAM=${1,,} # always lower case ($1 param)
if [ ! -z "$2" ]; then
    DATEDIR=$(date +%Y/%m/%d --date="$2")
    if [ $? -ne 0 ]; then
        logger -t $loggertitle "[ERR] Issues with date provided. Cannot continue."
        exit
    fi
    LAPSEFILE="${CAM}_$(date +%Y%m%d --date="$2").mp4"
else
    DATEDIR=$(date +%Y/%m/%d --date="yesterday 13:00")
    LAPSEFILE="${CAM}_$(date +%Y%m%d --date="yesterday 13:00").mp4"
fi
maindir=$(jq -r .maindir <<< $CONFIG)
ALLJPEGS="$maindir/$CAM/$DATEDIR"
LAPSEDIR="$maindir/dailytimelapses"

if [ ! -d $ALLJPEGS ]; then
    echo "[ERR] Directory $ALLJPEGS does not exist or you provided incorrect \$1 and \$2 parameters"
    exit
fi

if [ ! -d $LAPSEDIR ]; then
    mkdir -v -p $LAPSEDIR | logger -t $loggertitle
fi

if [ "$3" == "forcefroms3" ]; then
    # download everything from S3
    s3bucket="s3://"$(jq -r .aws.s3 <<< $CONFIG)"/$CAM/$DATEDIR"
    s3sync="aws s3 sync $s3bucket/ $ALLJPEGS/ --exclude=* --include=*.jpg"
    logger -t $loggertitle "> $s3sync"
    eval $s3sync
    if [ $? -ne 0 ]; then
        logger -t $loggertitle "[ERR] AWS CLI s3 sync failed. Cannot continue."
        exit
    fi
fi

# if we are here we are good to make a timelapse!
ffmpeg="ionice -c2 -n 5 ffmpeg -r 20 -pattern_type glob -i \"$ALLJPEGS/*.jpg\" \
    -s hd1080 -vcodec libx264 -pix_fmt yuvj420p /tmp/$LAPSEFILE -y"
logger -t $loggertitle "> $ffmpeg"

eval $ffmpeg

if [ ${PIPESTATUS[0]} -eq 0 ]; then
    mv -fv /tmp/$LAPSEFILE $LAPSEDIR/$LAPSEFILE | logger -t $loggertitle
    logger -t $loggertitle "[OK] $LAPSEDIR/$LAPSEFILE"
    # now wipe the dir!
    rm -fr $ALLJPEGS 2>&1 | logger -t $loggertitle
else
    logger -t $loggertitle "[ERR] Failed to create $LAPSEDIR/$LAPSEFILE timelapse. FFMPEG exit code: $?"
    rm -fv "/tmp/$LAPSEFILE" 2>&1 | logger -t $loggertitle
fi
