#!/bin/bash

# quick access to this on AWSlOGS:
# https://eu-central-1.console.aws.amazon.com/cloudwatch/home?region=eu-central-1#logEventViewer:group=/var/log/messages;filter=%22create-timelapse%22;start=P1D

# dont do anything if process is already running
if [ $(pgrep -f ${0} | wc -l) -gt 2 ]; then
    echo "[WARN] Process of ${0} is already running"
    exit
fi

if [ -z "$1" ]; then
    echo "[ERR] Please specify \$1 parameter. Typically this is 'cam1'"
    exit
fi

loggertitle="$(basename ${0})[$$]"
CONFIG=$(cat /etc/rpi.json)
CAM=${1,,} # always lower case ($1 param)
if [ ! -z "$2" ]; then
    DATEDIR=$(date +%Y/%m/%d --date="$2")
    LAPSEFILE="${CAM}_$(date +%Y%m%d --date="$2").mp4"
else
    DATEDIR=$(date +%Y/%m/%d --date="yesterday 13:00")
    LAPSEFILE="${CAM}_$(date +%Y%m%d --date="yesterday 13:00").mp4"
fi
maindir=$(jq -r .maindir <<< $CONFIG)
ALLJPEGS="$maindir/$CAM/$DATEDIR"
LAPSEDIR="$maindir/dailytimelapses"

if [ ! -d $ALLJPEGS ]; then
    echo "[ERR] Directory $ALLJPEGS does not exist or you provided incorrect \$1 and \$2 parameters"
    exit
fi

if [ ! -d $LAPSEDIR ]; then
    mkdir -v -p $LAPSEDIR | logger -i -t $loggertitle
fi

# if we are here we are good to make a timelapse!
ffmpeg="ionice -c2 -n 5 ffmpeg -r 24 -pattern_type glob -i \"$ALLJPEGS/*.jpg\" \
    -s hd1080 -vcodec libx264 -pix_fmt yuvj420p /tmp/$LAPSEFILE -y"
logger -i -t $loggertitle "> $ffmpeg"

eval $ffmpeg

if [ ${PIPESTATUS[0]} -eq 0 ]; then
    mv -fv /tmp/$LAPSEFILE $LAPSEDIR/$LAPSEFILE | logger -i -t $loggertitle
    logger -i -t $loggertitle "[OK] $LAPSEDIR/$LAPSEFILE"
    # now wipe the dir!
    rm -fr $ALLJPEGS 2>&1 | logger -i -t $loggertitle
else
    logger -i -t $loggertitle "[ERR] Failed to create $LAPSEDIR/$LAPSEFILE timelapse. FFMPEG exit code: $?"
    rm -fv "/tmp/$LAPSEFILE" 2>&1 | logger -i -t $loggertitle
fi
