#!/bin/bash

maindir=$(cat /etc/rpi.json | jq -r .maindir)
aws_r53ttl=$(cat /etc/rpi.json | jq -r .aws.r53ttl)
aws_r53zoneid=$(cat /etc/rpi.json | jq -r .aws.r53zoneid)
aws_r53subd=$(cat /etc/rpi.json | jq -r .aws.r53subd)
aws_r53json=$(cat /etc/rpi.json | jq -r .aws.r53json)

if [ ! -d $maindir ]; then
    mkdir -v -p $maindir
    chmod -v 777 $maindir
fi

privateIP=$(hostname -I | xargs) # xargs there "trims" the returned string
publicIP=$(curl -s --max-time 5 http://ipecho.net/plain || curl -s --max-time 5 https://api.ipify.org/ | xargs)
publicIP_previous=$(cat $maindir/ip.json | jq -r ".pub")

if [ ! -z "$privateIP" ] && [ ! -z "$publicIP" ]; then
    # check if public IP changed from previous test
    if [ "${publicIP}" != "${publicIP_previous}" ]; then
        echo $(printf $aws_r53json "$aws_r53subd" "$aws_r53ttl" "$publicIP") \
            > /tmp/get-ip-change-batch.json
        cat /tmp/get-ip-change-batch.json | logger -t "get-ip Route53"
        aws route53 change-resource-record-sets --hosted-zone-id $aws_r53zoneid \
            --change-batch "file:///tmp/get-ip-change-batch.json" 2>&1 \
            | awk '{print}' ORS='' | logger -t get-ip
        if [ $? -ne 0 ]; then
            logger -t get-ip "[ERROR] Could not set public IP address on $2! AWS Route53 exit code: $?"
        else
            echo "{\"pri\":\"${privateIP}\",\"pub\":\"${publicIP}\"}" > $maindir/ip.json
            cat $maindir/ip.json | logger -t "get-ip $maindir/ip.json"
            rm -vf /tmp/get-ip-change-batch.json
        fi
    fi
else
    logger -t get-ip "[WARN] Could not determine private or public IP address!"
fi
