#!/bin/bash

loggertitle="$(basename ${0})[$$]"

CONFIG=$(cat /etc/rpi.json)
maindir=$(jq -r .maindir <<< $CONFIG)
aws_r53ttl=$(jq -r .aws.r53ttl <<< $CONFIG )
aws_r53zoneid=$(jq -r .aws.r53zoneid <<< $CONFIG )
aws_r53subd=$(jq -r .aws.r53subd <<< $CONFIG )
aws_r53json=$(jq -r .aws.r53json <<< $CONFIG )

if [ ! -d $maindir ]; then
    mkdir -v -p $maindir
    chmod -v 777 $maindir
fi

if [ -z "$aws_r53zoneid" ]; then
    echo "Configuration file does not have aws.r53zoneid set. Nothing to do."
fi

privateIP=$(hostname -I | xargs) # xargs there "trims" the returned string
publicIP=$(curl -s --max-time 5 http://ipecho.net/plain || curl -s --max-time 5 https://api.ipify.org/ | xargs)
publicIP_previous=$(cat $maindir/ip.json | jq -r ".pub")

if [ ! -z "$privateIP" ] && [ ! -z "$publicIP" ]; then
    # check if public IP changed from previous test
    if [ "${publicIP}" != "${publicIP_previous}" ]; then
        echo $(printf $aws_r53json "$aws_r53subd" "$aws_r53ttl" "$publicIP") \
            > /tmp/get-ip-change-batch.json
        cat /tmp/get-ip-change-batch.json | logger -t $loggertitle
        aws route53 change-resource-record-sets --hosted-zone-id $aws_r53zoneid \
            --change-batch "file:///tmp/get-ip-change-batch.json" 2>&1 \
            | awk '{print}' ORS='' | logger -t $loggertitle
        if [ ${PIPESTATUS[0]} -ne 0 ]; then
            logger -t $loggertitle "[ERR] Could not set public IP address on $2! AWS Route53 exit code: $?"
            # TODO: try once more 1 minute later
        else
            echo "{\"pri\":\"${privateIP}\",\"pub\":\"${publicIP}\"}" > $maindir/ip.json
            cat $maindir/ip.json | logger -t $loggertitle "$maindir/ip.json"
            rm -vf /tmp/get-ip-change-batch.json
        fi
    fi
else
    logger -t $loggertitle "[ERR] Could not determine private or public IP address!"
fi
