#!/bin/bash

loggertitle="$(basename ${0})[$$]"

# dont do anything if process is already running
if [ $(pgrep -f ${0} | wc -l) -gt 2 ]; then
    echo "[WARN] Process of ${0} is already running"
    logger -t $loggertitle "[WARN] Process of ${0} is already running"
    exit
fi

CONFIG=$(cat /etc/rpi.json)
ftpdir=$(jq -r .ftp.dir <<< $CONFIG)
s3bucket="s3://"$(jq -r .aws.s3 <<< $CONFIG)
maindir=$(jq -r .maindir <<< $CONFIG)

aws s3 mv "$ftpdir/" "$s3bucket/motion/" --exclude "*" --include "*.jpg" --include "*.mp4" \
    --recursive --only-show-errors 2>&1 | logger -t $loggertitle

if [ ${PIPESTATUS[0]} -ne 0 ]; then
    logger -t $loggertitle "[ERR] AWSCLI error code: ${PIPESTATUS[0]}"
else
    logger -t $loggertitle "[OK] All done."
fi
