#!/bin/bash

# quick access to this on AWSlOGS:
# https://eu-central-1.console.aws.amazon.com/cloudwatch/home?region=eu-central-1#logEventViewer:group=/var/log/messages;filter=%22retry-files%22;start=PT1H

if [ ! -f $1 ]; then
    echo "[ERR] File $1 does not exist. Cannot continue."
fi

CONFIG-$(cat /etc/rpi.json)
maindir=$(jq -r .maindir <<< $CONFIG)
filename=$(basename $1)

logger -ti retry-files "Taking file $1"
mv -fv $1 /tmp/ | logger -t retry-files

# now iterate through the file
oks=0;errs=0
while IFS='' read -r line || [[ -n "$line" ]]; do
    eval $line
    if [ $? -ne 0 ]; then
        logger -ti retry-files "[ERR:$?] $line"
        echo $line >> "$maindir/$filename"
        errs=$(($errs+1))
    else
        logger -ti retry-files "[OK] $line"
        oks=$(($oks+1))
    fi
done < "/tmp/$filename"

logger -ti retry-files "Summary: successfully retried $oks command(s). Failed $errs"
