#!/bin/bash

# quick access to this on AWSlOGS:
# https://eu-central-1.console.aws.amazon.com/cloudwatch/home?region=eu-central-1#logEventViewer:group=/var/log/messages;filter=%22retry-files%22;start=PT1H

if [ ! -f $1 ]; then
    echo "[ERR] File $1 does not exist. Cannot continue."
fi

CONFIG-$(cat /etc/rpi.json)
maindir=$(jq -r .maindir <<< $CONFIG)
retryfilename=$(basename $1)

mv -fv $1 /tmp/ | logger -t retry-files

# now iterate through the file
while IFS='' read -r line || [[ -n "$line" ]]; do
    eval $line
    if [ $? -ne 0 ]; then
        retrycmd="echo \"$line\" >> $maindir/$retryfilename"
        logger -t retry-files "[ERR] Something failed. Will retry once more:"
        logger -t retry-files "> $retrycmd"
        eval $retrycmd
    else
        logger -t retry-files "[OK] $line"
    fi
done < "/tmp/$retryfilename"
