#!/bin/bash

# set this to your own location
maindir=$(cat /etc/rpi.json | jq -r .maindir)
sunapi=$(cat /etc/rpi.json | jq -r .sun.api)
out="$maindir/sunrise-sunset-today.json"

if [ ! -d $maindir ]; then
    mkdir -v -p $maindir
    chmod -v 777 $maindir
fi

curl -m 10 -s -f "$sunapi" -o $out

if [ $? -eq 0 ]; then
    echo "$out written"
else
    logger -t sunrise-sunset-today "[WARN] Failed update $out file. CURL exit code: $?"
fi

cat $out | logger -t sunrise-sunset-today
