#!/bin/bash

# set this to your own location
lat=$(cat /etc/rpi.json | jq -r .lat)
lon=$(cat /etc/rpi.json | jq -r .lon)
maindir=$(cat /etc/rpi.json | jq -r .maindir)

if [ ! -d $maindir ]; then
    mkdir -v -p $maindir
    chmod -v 777 $maindir
fi
OUTFILE="$maindir/sunrise-sunset-today.json"

curl -m 10 -s "https://api.sunrise-sunset.org/json?lat=$lat&lng=$lon&date=today&formatted=0" -o $OUTFILE

if [ $? -eq 0 ]; then
    echo "$OUTFILE written"
fi

cat $OUTFILE | logger -t sunrise-sunset-today
