#!/bin/bash

# quick access to this on AWSlOGS:
# https://eu-central-1.console.aws.amazon.com/cloudwatch/home?region=eu-central-1#logEventViewer:group=/var/log/messages;filter=%22system-status%22;start=P1D

loggertitle="$(basename ${0})[$$]"

cpu_temp=$(</sys/class/thermal/thermal_zone0/temp)
cpu_temp=$(($cpu_temp/1000))

load_averages=$(ionice -c2 -n7 cut -d' ' -f-3 /proc/loadavg|sed -e "s/ /,/g")
disk_used_percent=$(ionice -c2 -n7 df / | awk '{print $5}' | cut -d '%' -f 1 | tail -n 1)

out="{\"host\":\"$HOSTNAME\",\"cpu_temp\":$cpu_temp,\"load_averages\":[$load_averages],\"disk_used_percent\":$disk_used_percent}"
echo "$out"
echo "$out" | logger -t $loggertitle
