#!/bin/bash

# quick access to this on AWSlOGS:
# https://eu-central-1.console.aws.amazon.com/cloudwatch/home?region=eu-central-1#logEventViewer:group=/var/log/messages;filter=%22system-status%22;start=P1D

loggertitle="$(basename ${0})[$$]"

cpu_temp=$(</sys/class/thermal/thermal_zone0/temp)
cpu_temp=$(($cpu_temp/1000))

load_times=$(ionice -c2 -n7 uptime | awk -F' *,? *' '{print "\"load1\":"$11",\"load5\":"$12",\"load15\":"$13}')

out="{\"host\":\"$HOSTNAME\",\"cpu_temp\":$cpu_temp,$load_times}"
echo "$out"
echo "$out" | logger -t $loggertitle
