#!/bin/bash

# quick access to this on AWSlOGS:
# https://eu-central-1.console.aws.amazon.com/cloudwatch/home?region=eu-central-1#logEventViewer:group=/var/log/messages;stream=RPI1;filter=%22weather-now%22;start=PT2H

loggertitle="$(basename ${0})[$$]"

CONFIG=$(cat /etc/rpi.json)
maindir=$(jq -r .maindir <<< $CONFIG)
jq_query1=$(jq -r .weather.jq_query1 <<< $CONFIG)
outraw="/tmp/weather-all.json"
out="$maindir/weather.json"
takecmd=$(jq -r .weather.takecmd <<< $CONFIG)
takecmd=$(printf "$takecmd" $outraw)

if [ ! -d $maindir ]; then
    mkdir -v -p $maindir
    chmod -v 777 $maindir
fi

logger -t $loggertitle "> $takecmd"
eval $takecmd

if [ $? -eq 0 ]; then
    jq -rc "$jq_query1" < $outraw > $out
else
    logger -t $loggertitle "[ERR] CURL exit code $?. Will use $out from previous run."
fi

logger -t $loggertitle < $out