#!/bin/bash

# quick access to this on AWSlOGS:
# https://eu-central-1.console.aws.amazon.com/cloudwatch/home?region=eu-central-1#logEventViewer:group=/var/log/messages;stream=RPI1;filter=%22weather-now%22;start=PT2H

CONFIG=$(cat /etc/rpi.json)
maindir=$(jq -r .maindir <<< $CONFIG)
weatherapi=$(jq -r .weather.api <<< $CONFIG)
jq_query1=$(jq -r .weather.jq_query1 <<< $CONFIG)
outraw="/tmp/weather-all.json"
out="$maindir/weather.json"

if [ ! -d $maindir ]; then
    mkdir -v -p $maindir
    chmod -v 777 $maindir
fi

curl -m 10 -s -f "$weatherapi" -o $outraw

if [ $? -eq 0 ]; then
    echo "$out written"
    # todo run jq query here
    jq -rc "$jq_query1" < $outraw > $out
    logger -t weather-now < $out
else
    logger -t weather-now "[WARN] Failed update $out file. CURL exit code: $?"
fi
